/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjetsDto {
  budget?: number;
  dateDebut?: string;
  dateFin?: string;
  description?: string;
  id?: number;
  nom?: string;
}
